name: Deployment Testing

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  compare:
    runs-on: ubuntu-latest
    env:
      METADATA_FILE_PATH: ./metadata/cq-metadata.json

    steps:
    - name: Print variable
      run: echo $LOCALVAR

    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Print metadata file content
      run: cat $METADATA_FILE_PATH
    
    - name: Compare Files
      run: |
        JSON=$(cat $METADATA_FILE_PATH)
        jq -c '.[]' <<< "$JSON" | while read obj; do
          FILE_NAME=$(jq -r '.name' <<< "$obj")
          LOCAL_PATH=$(jq -r '.localPath' <<< "$obj") 
          ENV_PATH=$(jq -r '.envPath' <<< "$obj")
          curl -o $FILE_NAME $ENV_PATH


          echo "Comparing file - $FILE_NAME"


          LOCAL_HASH=$(md5sum $LOCAL_PATH | cut -d ' ' -f 1)
          ENV_HASH=$(md5sum $FILE_NAME | cut -d ' ' -f 1)

          if ["$LOCAL_HASH" == "$ENV_HASH"]; then
            echo "$FILE_NAME is up to date"
          else
            echo "$FILE_NAME" is not up to date
          fi
        done