name: Deployment Testing

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  compare:
    runs-on: ubuntu-latest
    env:
      LOCALVAR: testing

    steps:
    - name: Print variable
      run: echo $LOCALVAR
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Print metadata file content
      run: cat ./metadata/cq-metadata.json