name: Deployment Testing

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  compare:
    runs-on: ubuntu-latest
    env:
      METADATA_FILE_PATH: ./metadata/cq-metadata.json

    steps:
    - name: Print variable
      run: echo $LOCALVAR

    - name: Checkout repository
      uses: actions/checkout@v2.3.4

    - name: Print metadata file content
      run: cat $METADATA_FILE_PATH
    
    - name: Compare Files
      run: |
        METADATA=$(cat $METADATA_FILE_PATH)
        jq -c '.[]' <<< "$METADATA" | while read obj; do
          FILE_NAME=$(jq -r '.name' <<< "$obj")
          LOCAL_PATH=$(jq -r '.localPath' <<< "$obj") 
          ENV_PATH=$(jq -r '.envPath' <<< "$obj")

          # Getting files ready
          LOCAL_FILE=$(cat $LOCAL_PATH)
          DEPLOYED_FILE=$(curl -s $ENV_PATH)

          # Formatting and sorting files
          LOCAL_FILE=$(echo "$LOCAL_FILE" | jq -S .)
          DEPLOYED_FILE=$(echo "$DEPLOYED_FILE" | jq -S .)

          # Comparing files
          echo "Comparing file - $FILE_NAME"
          OUTPUT=$(diff <(echo $LOCAL_FILE) <(echo $DEPLOYED_FILE))

          echo "output"
          echo "output $OUTPUT"

          # Printing output
          if [ -z "$OUTPUT" ]; then
            echo "$FILE_NAME is up to date"
          else
            echo "else block"
            echo "$FILE_NAME is not up to date"
            echo "$OUTPUT"
          fi
        done