name: Deployment Testing

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  compare:
    runs-on: ubuntu-latest
    env:
      METADATA_FILE_PATH: ./metadata/cq-metadata.json

    steps:
    - name: Print variable
      run: echo $LOCALVAR

    # - name: Install jq for using JSON
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y jq 

    - name: checkout repo
      uses: actions/checkout@v2.3.4

    - name: Print metadata file content
      run: cat $METADATA_FILE_PATH
    
    - name: Print file using jq
      run: |
        JSON=$(cat $METADATA_FILE_PATH)
        jq -c '.[]' <<< "$JSON" | while read obj; do
          FILE_NAME=$(jq -r '.name' <<< "$obj")
          LOCAL_PATH=$(jq -r '.localPath' <<< "$obj")
          ENV_PATH=$(jq -r '.envPath' <<< "$obj")
          FILE_FROM_ENV=$(curl -s $ENV_PATH)
          echo $FILE_NAME
          echo $FILE_FROM_ENV
          echo $LOCAL_PATH
        done